version: '2'
services:
  db:
    build: ./db
    volumes:
      - './db/pgdata:/pgdata'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
